import { Footer } from '@/components/structures/Footer/Footer';
import { META } from '@/constants/meta';

import { Metadata } from 'next';

export const metadata: Metadata & { title: string } = {
  title: META.siteName,
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <>
      <header className="py-8 sm:py-16 px-4 sm:pl-10 mb-4">
        <div className="max-w-[960px] mx-auto">
          <h1 className="text-2xl font-bold">{metadata.title}</h1>
        </div>
      </header>

      <main className="px-4 sm:pl-10">
        <div className="max-w-[960px] mx-auto">
          <h2 className="text-2xl mb-4">Introduction</h2>

          <p>
            Are putted together notes and miscellaneous notes put together related to front-end technology by developer
            who are not good at English. I usually use google translate often. This page is powered by{' '}
            <a href="https://github.com/hiroya-uga/hiroya-uga.github.io">GitHub Pages</a>. If there are mistakes such as
            typographical errors, please tell me using Issue.
          </p>

          <h2 className="text-2xl mb-4 mt-28">Documents</h2>

          <h3 className="font-bold mb-4">Translations</h3>

          <ul className="pl-5 mb-4">
            <li className="list-disc pl-1">
              <a href="documents/translations/pauljadam-modern-web-a11y-demos">
                日本語訳：PaulJAdam's Modern Web Accessibility Demos
              </a>
            </li>
          </ul>

          <h3 className="font-bold mb-4">Others</h3>

          <ul className="pl-5">
            <li className="list-disc pl-1">
              <a href="/documents/fantasized-specs">Fantasized Web Standards and Specifications</a>
            </li>
          </ul>

          <h2 className="text-2xl mb-8 mt-28">PROFILE</h2>

          <p>
            <a href="https://github.com/hiroya-uga">https://github.com/hiroya-uga</a>
          </p>
        </div>
      </main>

      <Footer />
    </>
  );
}
