import { ButtonInH2 } from '@/app/(pauljadam-modern-web-a11y-demos)/documents/translations/pauljadam-modern-web-a11y-demos/accordion-heading/Client';

import type { Metadata } from 'next';

export const metadata: Metadata & { title: string } = {
  title: '見出しがアコーディオンのフックの例',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <h1>{metadata.title}</h1>

      <h2>
        <ButtonInH2 />
      </h2>

      <div id="accordion-div" style={{ display: 'none' }}>
        表示されたコンテンツ
      </div>
    </>
  );
}
