export const SEO: Record<string, string> = {
  '/': 'Home',
  '/documents': '資料集',
  '/documents/ui-notes': 'UI Notes',
  '/documents/ui-notes/merchant-discount-price': '【HTML】割引などの金額変更で打ち消し線を表現するためのマークアップ',
  '/documents/translations': '日本語訳まとめ',
  '/documents/translations/w3c/wai/tutorials/images': '日本語訳：Images Tutorial',
  '/documents/translations/pauljadam-modern-web-a11y-demos': "日本語訳：PaulJAdam's Modern Web Accessibility Demos",
  '/documents/translations/pauljadam-modern-web-a11y-demos/a11y-gone-wrong': 'a11y-gone-wrong',
  '/documents/translations/pauljadam-modern-web-a11y-demos/abbr': 'abbr',
  '/documents/translations/pauljadam-modern-web-a11y-demos/accesskey': 'accesskey',
  '/documents/translations/pauljadam-modern-web-a11y-demos/accessiblenameimg': 'accessiblenameimg',
  '/documents/translations/pauljadam-modern-web-a11y-demos/csunmobile-accordion-bad': 'csunmobile-accordion-bad',
  '/documents/translations/pauljadam-modern-web-a11y-demos/csunmobile-accordion-aria': 'csunmobile-accordion-aria',
  '/documents/translations/pauljadam-modern-web-a11y-demos/accordion-heading': 'accordion-heading',
  '/documents/translations/pauljadam-modern-web-a11y-demos/accounting-tables': 'accounting-tables',
  '/documents/translations/pauljadam-modern-web-a11y-demos/alerttimer': 'alerttimer',
  '/documents/translations/pauljadam-modern-web-a11y-demos/altbgimg': 'altbgimg',
  '/documents/translations/pauljadam-modern-web-a11y-demos/annotated-tables': 'annotated-tables',
  '/documents/translations/pauljadam-modern-web-a11y-demos/apple-system-css-font': 'apple-system-css-font',
  '/documents/translations/pauljadam-modern-web-a11y-demos/aria-alert-assertive-validation':
    'aria-alert-assertive-validation',
  '/documents/translations/pauljadam-modern-web-a11y-demos/aria-alert-validation': 'aria-alert-validation',
  '/documents/translations/pauljadam-modern-web-a11y-demos/aria-atomic-relevant': 'aria-atomic-relevant',
  '/documents/translations/pauljadam-modern-web-a11y-demos/aria-describedby-labelledby-link-purpose':
    'aria-describedby-labelledby-link-purpose',
  '/documents/translations/pauljadam-modern-web-a11y-demos/aria-describedby-validation': 'aria-describedby-validation',
  '/documents/translations/pauljadam-modern-web-a11y-demos/aria-expanded': 'aria-expanded',
  // ['aria-haspopup', false],
  '/documents/translations/pauljadam-modern-web-a11y-demos/aria-hidden': 'aria-hidden',
  '/documents/translations/pauljadam-modern-web-a11y-demos/aria-invalid': 'aria-invalid',
  '/documents/translations/pauljadam-modern-web-a11y-demos/aria-labelledby': 'aria-labelledby',
  '/documents/translations/pauljadam-modern-web-a11y-demos/aria-live-slider': 'aria-live-slider',
  '/documents/translations/pauljadam-modern-web-a11y-demos/aria-menubar': 'aria-menubar',
  '/documents/translations/pauljadam-modern-web-a11y-demos/aria-pressed': 'aria-pressed',
  // ['aria-role-alertdialog-setTimeout', false],
  // ['aria-role-alertdialog', false],
  // ['aria-role-tooltip', false],
  // ['aria-roledescription', false],
  // ['aria-table', false],
  // ['aria-tabpanel', false],
  '/documents/translations/pauljadam-modern-web-a11y-demos/ariacountdown': 'ariacountdown',
  // ['audio-slider', false],
  // ['autofocusvstabindex', false],
  '/documents/translations/pauljadam-modern-web-a11y-demos/autoplay-loop-muted-controls':
    'autoplay-loop-muted-controls',
  '/documents/translations/pauljadam-modern-web-a11y-demos/badav': 'badav',
  '/documents/translations/pauljadam-modern-web-a11y-demos/bootstrap-dropdown': 'bootstrap-dropdown',
  // ['button', false],
  '/documents/translations/pauljadam-modern-web-a11y-demos/buttons': 'buttons',
  // ['canvas', false],
  '/documents/translations/pauljadam-modern-web-a11y-demos/checkbox': 'checkbox',
  // ['bootcamp-contact-before', false],
  // ['bootcamp-contact-after-aria', false],
  // ['bootcamp-contact-after-html5', false],
  '/documents/translations/pauljadam-modern-web-a11y-demos/css-content-new-window': 'css-content-new-window',
  // ['css-line-through-del-ins-accessibility', false],
  // ['css3speech', false],
  '/documents/translations/pauljadam-modern-web-a11y-demos/css4altgeneratedcontent': 'css4altgeneratedcontent',
  // ['csstext', false],
  // ['customcontrols', false],
  // ['dates', false],
  // ['data-tables', false],
  '/documents/translations/pauljadam-modern-web-a11y-demos/detail-message-dialog': 'detail-message-dialog',
  // ['details-summary', false],
  '/documents/translations/pauljadam-modern-web-a11y-demos/dialog': 'dialog',
  // ['dialog-DOM', false],
  // ['draggable', false],
  '/documents/translations/pauljadam-modern-web-a11y-demos/empty-headings': 'empty-headings',
  '/documents/translations/pauljadam-modern-web-a11y-demos/fake-button': 'fake-button',
  // ['focus-after-page-load', false],
  '/documents/translations/pauljadam-modern-web-a11y-demos/figure-figcaption': 'figure-figcaption',
  // ['csunmobile-form-bad', false],
  // ['csunmobile-form-aria', false],
  // ['csunmobile-form-html5', false],
  // ['form-errors-top', false],
  // ['fieldsetlegend', false],
  // ['focusvisible', false],
  '/documents/translations/pauljadam-modern-web-a11y-demos/goodav': 'goodav',
  // ['hamburger-menu', false],
  // ['headings', false],
  // ['highlights', false],
  // ['html5-input-types', false],
  // ['html5-placeholder-contrast', false],
  // ['html5-structural', false],
  // ['html5-video-a11y', false],
  // ['iframe', false],
  // ['iframe-voiceover-scrolling-bug', false],
  // ['imageAndTextLink', false],
  // ['img', false],
  // ['inpagelinks', false],
  // ['inputSubmitTitle', false],
  // ['ios8bugs', false],
  // ['iosvocheatsheet', false],
  // ['jaws-ie-tabindex-bug', false],
  // ['jsalertconfirmprompt', false],
  // ['jqueryui-autocomplete', false],
  // ['landmarks', false],
  // ['layout-table-role-presentation', false],
  // ['linkpurpose', false],
  // ['loading-indicator', false],
  // ['mathml', false],
  // ['missingfieldsetlegend', false],
  // ['mobilechecklist', false],
  // ['mobileforma11y', false],
  // ['multithumb-slider', false],
  // ['numericRanges', false],
  // ['obstacle-course', false],
  // ['parsing', false],
  // ['positionbug', false],
  // ['positivetabindexfail', false],
  // ['progressbar', false],
  // ['quad', false],
  // ['repeating-buttons-accessibilty', false],
  // ['remove-filter-buttons', false],
  // ['rolegroup', false],
  // ['role-alert', false],
  // ['rwd-aria-menu-button', false],
  // ['rwd-aria-menubar', false],
  // ['rwd-tabs-accordion', false],
  // ['rwdstate', false],
  // ['section', false],
  // ['select', false],
  // ['select-android', false],
  // ['select-option', false],
  // ['semanticelements', false],
  // ['semanticmobile', false],
  // ['session-timeout-alertdialog', false],
  // ['spa-focus', false],
  // ['svg', false],
  // ['svg-bar-chart', false],
  // ['svg-line-chart', false],
  // ['tableA11yTest', false],
  // ['talkbackcheatsheet', false],
  // ['timeout', false],
  // ['title-aria-label', false],
  // ['title-keyboard', false],
  // ['tooltip', false],
  // ['underlines', false],
  // ['voiceover-clickable', false],
  // ['voiceover-ios-html-aria-support', false],
  // ['voiosmultifocusbug', false],
  // ['web-speech-api', false],
  // ['youtubeHTML5embed', false],
  '/documents/media': 'Media',
  '/documents/fantasized-specs': 'Fantasized specs',
  '/documents/fantasized-specs/html-carousel': 'The Carousel element',
  '/documents/fantasized-specs/css-observer': 'CSS Observer Module level 1',
  '/tools': 'ツール集',
  '/tools/an-alt-decision-tree': '代替テキスト２択チャート',
  '/tools/character-count': '文字数カウント',
  '/tools/accessible-name-and-description-computation': 'Accessible Name and Description Computation Playground',
  '/tools/css-units': 'CSS Units Playground',
  '/tools/dom-events-watcher': 'DOM Event Playground',
  '/tools/touch-event-touches': 'TouchEvent.touches Playground',
};
