import { DocumentScript } from '@/app/(pauljadam-modern-web-a11y-demos)/documents/translations/pauljadam-modern-web-a11y-demos/ariacountdown/DocumentScript';

import type { Metadata } from 'next';

export const metadata: Metadata & { title: string } = {
  title: 'ARIAを使ったカウントダウンタイマー',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <h1>{metadata.title}</h1>

      <DocumentScript />

      <p>HH:MM:SS</p>
      <p>ARIA Live Regionsを使って、毎分の変化を読み上げさせる例です。</p>

      <h2>保存までの残り時間:</h2>

      <span id="timer" data-seconds="32400" className="countdown">
        09:00:00
      </span>
      <div
        id="alert"
        role="alert"
        aria-live="assertive"
        style={{ position: 'absolute', width: 0, height: 0, clip: 'rect(0,0,0,0)' }}
      ></div>
    </>
  );
}
