import type { Metadata } from 'next';

export default function Page() {
  return (
    <>
      <h1>Fantasized specs</h1>

      <p className="my-4">These are the spec proposals that I came up with in my daily work.</p>
      <p>日々業務の中で思いついた「あんかこといいなできたらいいな」集。</p>

      <ul className="pl-5">
        <li className="list-disc pl-1">
          <a href="/documents/fantasized-specs/html-carousel">The Carousel element</a>
        </li>
        <li className="list-disc pl-1">
          <a href="/documents/fantasized-specs/css-observer">CSS Observer</a>
        </li>
      </ul>
    </>
  );
}

export const metadata: Metadata & { title: string } = {
  title: '!Create Next App',
  description: 'Generated by create next app',
};
