export const UNSUPPORTED_LABEL = '__undefined__';

export const MQ_LIST = [
  '(prefers-color-scheme: dark)',
  '(prefers-color-scheme: light)',
  '(prefers-reduced-motion: reduce)',
  '(prefers-contrast: more)',
  '(prefers-contrast: less)',
  '(prefers-contrast: custom)',
  '(prefers-reduced-transparency: reduce)',
  '(forced-colors: active)',
  '(inverted-colors: inverted)',
  '(color-gamut: srgb)',
  '(color-gamut: p3)',
  '(color-gamut: rec2020)',
  '(dynamic-range: high)',
  '(hover: hover)',
  '(any-hover: hover)',
  '(pointer: fine)',
  '(pointer: coarse)',
  '(any-pointer: fine)',
  '(any-pointer: coarse)',
  '(orientation: portrait)',
  '(orientation: landscape)',
  '(display-mode: standalone)',
  '(display-mode: minimal-ui)',
  '(display-mode: fullscreen)',
  '(display-mode: window-controls-overlay)',
  '(display-mode: browser)',
] as const;

/**
 * PermissionName は lib.dom 上で型が狭いため、ブラウザ実装に合わせて広めに扱う。
 * 未対応の name は query() で例外 → 'unsupported' になるだけなので、網羅的に列挙する。
 */
export const PERMISSION_NAMES = [
  'accelerometer',
  'ambient-light-sensor',
  'background-fetch',
  'background-sync',
  'bluetooth',
  'camera',
  'captured-surface-control',
  'clipboard-read',
  'clipboard-write',
  'compute-pressure',
  'display-capture',
  'geolocation',
  'gyroscope',
  'idle-detection',
  'local-fonts',
  'magnetometer',
  'microphone',
  'midi',
  'nfc',
  'notifications',
  'payment-handler',
  'persistent-storage',
  'push',
  'screen-wake-lock',
  'speaker-selection',
  'storage-access',
  'system-wake-lock',
  'top-level-storage-access',
  'window-management',
] as const;
