import { DocumentScript } from '@/app/(pauljadam-modern-web-a11y-demos)/documents/translations/pauljadam-modern-web-a11y-demos/checkbox/DocumentScript';
import '@/app/(pauljadam-modern-web-a11y-demos)/documents/translations/pauljadam-modern-web-a11y-demos/checkbox/page.css';

import type { Metadata } from 'next';

export default function Page() {
  return (
    <>
      <DocumentScript />

      <h1>WAI-ARIAを利用したものと純粋なチェックボックスの比較</h1>
      <p>
        <a href="http://www.w3.org/TR/wai-aria-practices-1.1/#checkbox">
          http://www.w3.org/TR/wai-aria-practices-1.1/#checkbox
        </a>
      </p>

      <h2>純粋なチェックボックス</h2>

      <label>
        <input type="checkbox" />
        <span>同意する場合はチェックを入れてください。</span>
      </label>

      <h2>非アクセシブルなマウス専用のチェックボックス</h2>

      <span id="spancheckbox" className="unchecked">
        同意する場合はチェックを入れてください。
      </span>

      <h2>ARIA Checkbox</h2>

      <span className="unchecked" role="checkbox" aria-checked="false" tabIndex={0}>
        同意する場合はチェックを入れてください。
      </span>
    </>
  );
}

export const metadata: Metadata = {
  title: 'アクセシブル施策の失敗例',
  description: 'Generated by create next app',
};
